// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guide: [{ type: "autogenerated", dirName: "guide" }],
  quickstart: [{ type: "autogenerated", dirName: "quickstart" }]
};

module.exports = sidebars;
